-- AlterTable
ALTER TABLE "ChildSettings" ADD COLUMN     "splitEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "splitGivePct" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "splitSavePct" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "splitSpendPct" DOUBLE PRECISION NOT NULL DEFAULT 100;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "giveBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saveBalance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "spendBalance" DOUBLE PRECISION NOT NULL DEFAULT 0;
