export const mockFamily = {
  name: 'Famille Dupont',
  parent: { id: 'p1', name: 'Sarah', email: 'sarah@dupont.fr', avatar: 'S' },
  children: [
    { id: 'c1', name: 'Alice', age: 8, avatar: 'A', balance: 127.50, color: '#7B61FF', monthDelta: 15 },
    { id: 'c2', name: 'Bob', age: 11, avatar: 'B', balance: 214.00, color: '#2E75B6', monthDelta: 22 },
    { id: 'c3', name: 'Claire', age: 14, avatar: 'C', balance: 400.00, color: '#10B981', monthDelta: 30 },
  ],
};

export const mockChores = [
  {
    id: 'ch1',
    title: 'Laver la vaisselle',
    description: 'Laver et sécher tous les plats, verres et couverts après le dîner.',
    reward: 15,
    assigneeId: 'c1',
    deadline: 'Demain, 18h00',
    status: 'submitted',
    submittedAt: 'Il y a 2h',
    note: 'Vaisselle faite, tout est propre !',
  },
  {
    id: 'ch2',
    title: 'Faire le lit',
    description: 'Faire son lit correctement chaque matin avant 10h.',
    reward: 5,
    assigneeId: 'c1',
    deadline: "Aujourd'hui, 10h00",
    status: 'pending',
    submittedAt: null,
    note: null,
  },
  {
    id: 'ch3',
    title: 'Tondre la pelouse',
    description: 'Tondre toute la pelouse du jardin arrière et ramasser les déchets.',
    reward: 30,
    assigneeId: 'c3',
    deadline: 'Ce week-end',
    status: 'submitted',
    submittedAt: 'Il y a 30 min',
    note: 'Pelouse bien tondue !',
  },
  {
    id: 'ch4',
    title: 'Ranger la chambre',
    description: 'Ranger tous les jouets, vêtements et affaires de bureau.',
    reward: 10,
    assigneeId: 'c2',
    deadline: 'Hier',
    status: 'completed',
    submittedAt: 'Hier',
    note: null,
  },
  {
    id: 'ch5',
    title: 'Sortir les poubelles',
    description: 'Sortir les poubelles pour la collecte du lundi matin.',
    reward: 8,
    assigneeId: 'c2',
    deadline: 'Hier',
    status: 'rejected',
    submittedAt: 'Hier',
    note: null,
    rejectionReason: "Les poubelles n'ont pas été sorties correctement.",
  },
  {
    id: 'ch6',
    title: 'Aspirateur salon',
    description: "Passer l'aspirateur dans le salon et la salle à manger.",
    reward: 12,
    assigneeId: 'c2',
    deadline: 'Vendredi, 20h00',
    status: 'pending',
    submittedAt: null,
    note: null,
  },
  {
    id: 'ch7',
    title: 'Débarrasser la table',
    description: 'Débarrasser la table après chaque repas.',
    reward: 3,
    assigneeId: 'c1',
    deadline: "Aujourd'hui, 21h00",
    status: 'pending',
    submittedAt: null,
    note: null,
  },
  {
    id: 'ch8',
    title: 'Arroser les plantes',
    description: 'Arroser toutes les plantes du salon et de la cuisine.',
    reward: 6,
    assigneeId: 'c3',
    deadline: 'Jeudi',
    status: 'pending',
    submittedAt: null,
    note: null,
  },
];

export const mockRules = [
  { id: 'r1', title: 'Retard corvée', description: 'Corvée non faite dans les délais impartis', amount: 5, active: true },
  { id: 'r2', title: 'Mauvais comportement', description: 'Comportement inacceptable à la maison', amount: 10, active: true },
  { id: 'r3', title: 'Notes scolaires', description: 'Note inférieure à 10/20', amount: 8, active: false },
  { id: 'r4', title: 'Mensonge', description: 'Avoir menti sur une corvée ou une situation', amount: 15, active: true },
];

export const mockTransactions = {
  c1: [
    { id: 't1', type: 'chore', desc: 'Laver la vaisselle', amount: 15, date: 'Hier' },
    { id: 't2', type: 'allowance', desc: 'Argent de poche hebdo', amount: 10, date: 'Lundi' },
    { id: 't3', type: 'penalty', desc: 'Retard corvée - Faire le lit', amount: -5, date: 'Dimanche' },
    { id: 't4', type: 'chore', desc: 'Faire le lit (×5)', amount: 25, date: 'Semaine dernière' },
    { id: 't5', type: 'allowance', desc: 'Argent de poche hebdo', amount: 10, date: 'Il y a 2 semaines' },
  ],
  c2: [
    { id: 't6', type: 'chore', desc: 'Ranger la chambre', amount: 10, date: 'Hier' },
    { id: 't7', type: 'allowance', desc: 'Argent de poche hebdo', amount: 15, date: 'Lundi' },
    { id: 't8', type: 'chore', desc: 'Aspirateur salon', amount: 12, date: 'Vendredi' },
    { id: 't9', type: 'penalty', desc: 'Poubelles mal sorties', amount: -8, date: 'Dimanche' },
  ],
  c3: [
    { id: 't10', type: 'chore', desc: 'Tondre la pelouse', amount: 30, date: "Aujourd'hui" },
    { id: 't11', type: 'allowance', desc: 'Argent de poche mensuel', amount: 50, date: '1er Avril' },
    { id: 't12', type: 'chore', desc: 'Arroser les plantes (×4)', amount: 24, date: 'Semaine dernière' },
  ],
};

export const mockGoals = {
  c1: [
    { id: 'g1', title: 'Nintendo Switch', target: 300, current: 127.50, icon: 'game' },
  ],
  c2: [
    { id: 'g2', title: 'Vélo tout terrain', target: 250, current: 214.00, icon: 'bike' },
    { id: 'g3', title: 'Cours de guitare', target: 80, current: 80, icon: 'music' },
  ],
  c3: [
    { id: 'g4', title: 'Smartphone', target: 500, current: 400, icon: 'phone' },
  ],
};

export const mockExpenseRequests = [
  {
    id: 'er1',
    childId: 'c1',
    title: 'Jeu Nintendo Switch',
    amount: 45,
    type: 'online',
    reference: 'amazon.fr/mario-kart-8',
    description: "Mario Kart 8 Deluxe, j'en ai vraiment envie depuis longtemps",
    status: 'pending',
    createdAt: 'Hier',
    approvedAmount: null,
    rejectionReason: null,
  },
  {
    id: 'er2',
    childId: 'c2',
    title: 'Jeu Steam - Minecraft',
    amount: 20,
    type: 'online',
    reference: 'store.steampowered.com',
    description: 'Tous mes amis y jouent',
    status: 'approved',
    createdAt: 'Il y a 3 jours',
    approvedAmount: 20,
    rejectionReason: null,
  },
  {
    id: 'er3',
    childId: 'c1',
    title: 'Baskets Nike Air Max',
    amount: 120,
    type: 'other',
    reference: '',
    description: 'Pour le sport scolaire',
    status: 'rejected',
    createdAt: 'Il y a 1 semaine',
    approvedAmount: null,
    rejectionReason: 'Tu as déjà des chaussures neuves. Trop cher pour le moment.',
  },
  {
    id: 'er4',
    childId: 'c3',
    title: 'Retrait cash sortie amis',
    amount: 25,
    type: 'cash',
    reference: '',
    description: 'Sortie au parc avec les copines samedi',
    status: 'pending',
    createdAt: "Aujourd'hui",
    approvedAmount: null,
    rejectionReason: null,
  },
  {
    id: 'er5',
    childId: 'c2',
    title: 'Pull gris Zara',
    amount: 35,
    type: 'imposed',
    reference: '',
    description: 'Acheté aux courses',
    status: 'completed',
    createdAt: 'Lundi',
    approvedAmount: 35,
    rejectionReason: null,
  },
];

export const analyticsData = {
  monthly: [
    { month: 'Oct', alice: 45, bob: 67, claire: 80 },
    { month: 'Nov', alice: 55, bob: 72, claire: 90 },
    { month: 'Déc', alice: 80, bob: 85, claire: 95 },
    { month: 'Jan', alice: 60, bob: 90, claire: 100 },
    { month: 'Fév', alice: 70, bob: 95, claire: 110 },
    { month: 'Mar', alice: 75, bob: 100, claire: 120 },
  ],
};
